services:
  - type: web
    name: douyin-extractor
    env: python
    buildCommand: pip install -r backend/requirements.txt && playwright install chromium
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0